Jagua/Controllers/PermisosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JaguaEntityModel;
using PagedList;

namespace Jagua.Controllers
{
    public class PermisosController : Controller
    {
        private JaguaEntities db = new JaguaEntities();

        // GET: Permisos
        public ActionResult Index(int? page)
        {
            List<permiso> listado = new List<permiso>();
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1; //operador ternario de consulta
            listado = db.permiso.OrderBy(n => n.nombre).ToList();
            return View(listado.ToPagedList(pageIndex, pageSize));
        }

        [HttpPost]
        public ActionResult Index(FormCollection fc, int? page)
        {
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

            List<permiso> listado = new List<permiso>();
            listado = db.permiso.OrderBy(n => n.nombre).ToList();
            var nombre = fc["searchString"]; // A traves del fc, obtengo el valor de la caja de texto


            if (!string.IsNullOrEmpty(nombre)) // pregunto si no esta vacio la variable nombre
            {
                listado = listado.Where(q => q.nombre.ToLower().Contains(nombre.ToLower())).ToList();//pregunta si el campo es igual al filtro
            }
            //aca le asigno a la cajita la variable que contiene la busqueda, para que aparezca al retornar
            ViewBag.searchString = nombre;

            //retorno la vista filtrada
            return View(listado.ToPagedList(pageIndex, pageSize));

        }
  
        // GET: Permisos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            permiso permiso = db.permiso.Find(id);
            if (permiso == null)
            {
                return HttpNotFound();
            }
            return View(permiso);
        }

        // GET: Permisos/Create
        public ActionResult Create()
        {
            permiso model = new permiso();
            return View(model);
        }

        // POST: Permisos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_permiso,nombre,descripcion")] permiso permiso)
        {
            if (ModelState.IsValid)
            {
                db.permiso.Add(permiso);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(permiso);
        }

        // GET: Permisos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            permiso permiso = db.permiso.Find(id);
            if (permiso == null)
            {
                return HttpNotFound();
            }
            return View(permiso);
        }

        // POST: Permisos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_permiso,nombre,descripcion")] permiso permiso)
        {
            if (ModelState.IsValid)
            {
                db.Entry(permiso).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(permiso);
        }

        // GET: Permisos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            permiso permiso = db.permiso.Find(id);
            if (permiso == null)
            {
                return HttpNotFound();
            }
            return View(permiso);
        }

        // POST: Permisos/Delete/5
        [HttpPost, ActionName("Delete")]      
        public ActionResult DeleteConfirmed(int id)
        {
            permiso permiso = db.permiso.Find(id);
            db.permiso.Remove(permiso);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Jagua/Views/Permisos/Create.cshtml
@model JaguaEntityModel.permiso

@{
    ViewBag.Title = "Create";
}
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        button {
            background: none;
            border: 0;
            color: #23CCEF;
        }
    </style>
</head>
<div class="card table-with-links table-responsive">
    <div class="card-header">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Nuevo Permiso</h4>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="pull-right">
                <button type="submit" title="Guardar" class="btn btn-wd btn-facebook">
                    <i class="fa fa-check-square-o"></i>
                    Guardar
                </button>
                <a href="@Url.Action("Index", "Permisos")" title="" class="btn btn-wd btn-info btn-outline" style="" data-original-title="Atras">
                    Cancelar
                </a>
            </div>

        </div>
        }

      

    </div>
</div>

Jagua/Views/Permisos/Edit.cshtml
@model JaguaEntityModel.permiso

@{
    ViewBag.Title = "Edit";
}
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        button {
            background: none;
            border: 0;
            color: #23CCEF;
        }
    </style>
</head>

<div class="card table-with-links table-responsive">
    <div class="card-header">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Editar Rol</h4>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id_permiso)
            <div class="form-group">
                @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="pull-right">
                <button type="submit" title="Guardar" class="btn btn-wd btn-facebook">
                    <i class="fa fa-check-square-o"></i>
                    Guardar
                </button>
                <a href="@Url.Action("Index", "Permisos")" title="" class="btn btn-wd btn-info btn-outline" style="" data-original-title="Atras">
                    Cancelar
                </a>
            </div>
        </div>
        }



    </div>
</div>

Jagua/Views/Permisos/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<JaguaEntityModel.permiso>

@{
    ViewBag.Title = "Index";
    var permisos = Jagua.Clases.SessionManager.ValidarPermisos("usuarios");
    var Insert = (permisos != null ? permisos.insertar : false);
    var Editar = (permisos != null ? permisos.modificar : false);
    var Eliminar = (permisos != null ? permisos.eliminar : false);
    var Ejecutar = (permisos != null ? permisos.ejecutar : false);
}

<head>
    <script type="text/javascript">
        $(document).ready(function () {
            $("[name=btnBuscar]").click(function () {
                $("#frmList").attr("action", "/Usuarios/Index/");
                $("#frmList").submit();

            });
        });
    </script>

    <!--En esta parte se define el estilo del botón de búsqueda-->
    <style>
        button {
            background: none; /*no tiene color de fondo*/
            border: 0; /*no tiene borde*/
        }
    </style>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width" />
    <!--Bootstrap css cdn--->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!---Jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <!--Bootstrap js cdn-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
</head>

<body>
    <div class="card table-with-links table-responsive">
        <div class="card-header">
            @if (!Ejecutar)
            {
                <script>
                    alert("Usted no tiene permisos para ver esta página consulte con el Administrador!");
                    location.href = "/Home"
                </script>
            }
            @using (Html.BeginForm("Index", "Permiso", FormMethod.Post, new { id = "frmList" }))
            {
                <div class="pull-right">
                    @if (Insert)
                    {
                        <a href="@Url.Action("Create") " rel="tooltip" title="" class="fa fa-user-plus" style="font-size: 22px; margin-top:60px; padding-right:40px" data-original-title="Nuevo Usuario"></a>
                    }
                    </div>
                <h2>Permisos</h2>
                <div class="row">
                    <div class="col-sm-3">
                        @Html.TextBox("searchString", (String)ViewBag.searchString, new { @class = "form-control", @placeholder = "Buscar..." })
                    </div>
                    <button type="submit" name="btnBuscar" title="Buscar registros" class="btn btn-simple btn-success btn-outline" style="">
                        <i class="nc-icon nc-zoom-split icon-bold" style="font-size: 20px" aria-hidden="true"></i>
                    </button>
                </div>
            }
        </div>
    </div>

    <div class="card table-responsive">
        <div class="card-body table-responsive">
            <table class="table">
                <tr>
                    <th>
                        Nombre
                    </th>
                    <th>
                       Descripción
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    using (Html.BeginForm("Delete", "Permiso", new { id = item.id_permiso }))
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.descripcion)
                        </td>
                        <td class="td-actions text-right">
                            @if (Editar)
                            {
                                <a href="@Url.Action("Edit", new { id = item.id_permiso })" rel="tooltip" title="" class="btn btn-success btn-link btn-xs" data-original-title="Editar">
                                    <i class="fa fa-edit"></i>
                                </a>
                            }
                            @if (Eliminar)
                            {
                                <button type="submit" value="Delete" onclick="return confirm('Está seguro de eliminar?') " rel="tooltip" title="" class="btn btn-danger btn-link btn-xs" data-original-title="Eliminar" />
                                <i class="fa fa-times"></i>
                            }
                            </td>
                    </tr>
                    }
                }

            </table>

            <div class="pull-right">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                @Html.PagedListPager(Model, page => Url.Action("Index",
                   new { page, currentFilter = ViewBag.CurrentFilter }))
            </div>
        </div>
    </div>
</body>