Jagua/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Jagua.Clases;
using JaguaEntityModel;
using PagedList;

namespace Jagua.Controllers
{
    public class RolesController : Controller
    {
        private JaguaEntities db = new JaguaEntities();

        // GET: Roles
        public ActionResult Index(int? page)
        {
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1; //operador ternario de consulta
            var datos = db.rol.OrderBy(n => n.nombre).ToList();
            return View(datos.ToPagedList(pageIndex, pageSize));
        }

        [HttpPost]
        public ActionResult Index(FormCollection fc, int? page)
        {
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

            var datos = db.rol.OrderBy(n => n.nombre).ToList();
            var nombre = fc["searchString"]; // A traves del fc, obtengo el valor de la caja de texto


            if (!string.IsNullOrEmpty(nombre)) // pregunto si no esta vacio la variable nombre
            {
                datos = datos.Where(q => q.nombre.ToLower().Contains(nombre.ToLower())).ToList();//pregunta si el campo es igual al filtro
            }
            //aca le asigno a la cajita la variable que contiene la busqueda, para que aparezca al retornar
            ViewBag.searchString = nombre;

            //retorno la vista filtrada
            return View(datos.OrderBy(n => n.nombre).ToPagedList(pageIndex, pageSize));

        }


        // GET: Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_rol,nombre,descripcion")] rol rol)
        {
            if (ModelState.IsValid)
            {
                db.rol.Add(rol);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rol);
        }

        // GET: Roles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            rol rol = db.rol.Find(id);
            if (rol == null)
            {
                return HttpNotFound();
            }
            return View(rol);
        }

        // POST: Roles/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_rol,nombre,descripcion")] rol rol)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rol).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rol);
        }

        // GET: Roles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            rol rol = db.rol.Find(id);
            if (rol == null)
            {
                return HttpNotFound();
            }
            return View(rol);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            using (var context = new JaguaEntities())
            {
                using (var dbContextTransaction = context.Database.BeginTransaction())
                {
                    try
                    {
                        IList<rol_pagina> rolPagina = (from rp in context.rol_pagina
                                                       where rp.id_rol == id
                                                       select rp).ToList();
                        if (rolPagina.Any())
                        {
                            context.rol_pagina.RemoveRange(rolPagina);
                            context.SaveChanges();
                        }
                        rol rol = context.rol.Find(id);
                        if (rol != null)
                        {
                            context.rol.Remove(rol);
                            context.SaveChanges();
                        }

                        dbContextTransaction.Commit();
                    }
                    catch (Exception ex)
                    {

                        dbContextTransaction.Rollback();
                        Clases.Logger.Log.ErrorFormat("ERROR DeleteConfirmed RolesController: {0}, {1}, {2}", ex.Message, ex.InnerException, ex.StackTrace);

                    }
                }
            }


            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public async Task<ActionResult> AgregarPermisos(int id)
        {
            rol rol_permiso = await db.rol.FindAsync(id);
            int idRol = 0;
            if (rol_permiso != null)
            {
                idRol = rol_permiso.id_rol;
            }
            var permisos = await db.paginas.ToListAsync();
            var Listado = new List<DatosPermisos>();
            rol_pagina valaccion = new rol_pagina();
            foreach (var item in permisos)
            {
                valaccion = ObtenerPermisos(item.id_pagina, idRol);
                Listado.Add(new DatosPermisos
                {
                    id_pagina = item.id_pagina,
                    nombre = item.pagina,
                    insert = (valaccion != null ? valaccion.insertar.Value : false),
                    update = (valaccion != null ? valaccion.modificar.Value : false),
                    delete = (valaccion != null ? valaccion.eliminar.Value : false),
                    ejecutar = (valaccion != null ? valaccion.ejecutar.Value : false)
                });


            }
            ViewBag.id_rol = new SelectList(db.rol, "id_rol", "nombre", idRol);
            ViewBag.Listado = Listado;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> AgregarPermisos(int id, int idPermiso, int idRol, string accion, string insertar,
            string actualizar, string eliminar, string ejecutar)
        {
            bool success = true;
            string mensaje = string.Empty;
            try
            {
                var rolpermiso = await db.rol_pagina.Where(t => t.id_pagina == idPermiso && t.id_rol == idRol).ToListAsync();
                if (!rolpermiso.Any())
                {
                    rol_pagina rolpagina = new rol_pagina();
                    rolpagina.id_rol = idRol;
                    rolpagina.id_pagina = idPermiso;
                    rolpagina.insertar = (insertar == "S" ? true : false);
                    rolpagina.modificar = (actualizar == "S" ? true : false);
                    rolpagina.eliminar = (eliminar == "S" ? true : false);
                    rolpagina.ejecutar = (ejecutar == "S" ? true : false);
                    db.rol_pagina.Add(rolpagina);
                    await db.SaveChangesAsync();

                }
                if (rolpermiso.Any())
                {
                    foreach (var item in rolpermiso)
                    {
                        item.insertar = (insertar == "S" ? true : false);
                        item.modificar = (actualizar == "S" ? true : false);
                        item.eliminar = (eliminar == "S" ? true : false);
                        item.ejecutar = (ejecutar == "S" ? true : false);
                        db.Entry(item).State = EntityState.Modified;
                        await db.SaveChangesAsync();

                    }
                }
                mensaje = "Permisos Agregado con exito!";

            }
            catch (Exception ex)
            {
                Logger.Log.Error("Error AgregarPermisos: " + ex.InnerException);
                success = false;
                mensaje = "Error al tratar de Agregar Permisos";
            }
            return Json(new { success, mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> AllAgregarPermisos(int id, int idPermiso, int idRol, string insertar,
           string actualizar, string eliminar, string ejecutar)
        {
            bool success = true;
            string mensaje = string.Empty;
            try
            {
                var rolpermiso = await db.rol_pagina.Where(t => t.id_pagina == idPermiso && t.id_rol == idRol).ToListAsync();
                if (!rolpermiso.Any())
                {
                    rol_pagina rolpagina = new rol_pagina();
                    rolpagina.id_rol = idRol;
                    rolpagina.id_pagina = idPermiso;
                    rolpagina.insertar = (insertar == "S" ? true : false);
                    rolpagina.modificar = (actualizar == "S" ? true : false);
                    rolpagina.eliminar = (eliminar == "S" ? true : false);
                    rolpagina.ejecutar = (ejecutar == "S" ? true : false);
                    db.rol_pagina.Add(rolpagina);

Jagua/Views/Roles/AgregarPermisos.cshtml
@{
    ViewBag.Title = "Agregar Permisos";
    var Listado = (List<Jagua.Controllers.DatosPermisos>)ViewBag.Listado;
}

<head>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>

        button {
            background: none;
            border: 0;
            color: #23CCEF;
        }
    </style>
</head>
<body>
    <script type="text/javascript">
        $(document).ready(function () {
            $("[name=btnBuscar]").click(function () {
                $("#frmList").attr("action", "/Usuarios/Index/");
                $("#frmList").submit();

            });
            $("#div_permisos").on('click', ':checkbox', function () {
                var $row = $(this).closest("tr");
                var id_permiso = parseInt($row.find("td:nth-child(6)").text());
                //var id_rolpermiso = parseInt($row.find("td:nth-child(3)").text());
                var id_rol = parseInt($("#id_rol").val());
                var acciones = "";
                var insertar = "N";
                var modificar = "N";
                var eliminar = "N";
                var ejecutar = "N";
                var ins = false;
                var mod = false;
                var del = false;
                var eje = false;
                var $g = $row.find("td:nth-child(2)");
                var $u = $row.find("td:nth-child(3)");
                var $d = $row.find("td:nth-child(4)");
                var $e = $row.find("td:nth-child(5)");
                $.each($g, function () {
                    ins = $g[0].children[0].checked;
                });
                $.each($u, function () {
                    mod = $u[0].children[0].checked;
                });
                $.each($d, function () {
                    del = $d[0].children[0].checked;
                });
                $.each($e, function () {
                    eje = $e[0].children[0].checked;
                });
                if (ins) {
                    acciones = "INS";
                    insertar = "S";
                } else {
                    acciones = "DEL";
                    insertar = "N";
                }
                if (mod) {
                    modificar = "S";
                }
                if (del) {
                    eliminar = "S";
                }
                if (eje) {
                    ejecutar = "S";
                }
                if (id_permiso > 0 && id_rol > 0) {
                    $.ajax({
                        url: "/Roles/AgregarPermisos/",
                        type: "POST",
                        data: {
                            id: 0,
                            idPermiso: id_permiso,
                            idRol: id_rol,
                            accion: acciones,
                            insertar: insertar,
                            actualizar: modificar,
                            eliminar: eliminar,
                            ejecutar: ejecutar
                        }
                    }).done(function (data) {
                        if (data.success) {
                            //$("#tblPermisos_ > tbody ").append(response.row);
                            swal("Agregar Permiso", data.mensaje, "success");
                        } else {
                            swal("Alerta!", data.mensaje, "warning");
                        }
                    });
                }
            });
            $("#btnGuardar").click(function () {
                //if ($("#ChkTodos").is(":checked")) {
                var agregar = false;
                $('#tblPermisos_ tr').each(function () {
                    var $row = $(this);//$(this).closest("tr");
                    var id_permiso = parseInt($row.find("td:nth-child(6)").text());
                    var id_rol = parseInt($("#id_rol").val());
                    var insertar = "N";
                    var modificar = "N";
                    var eliminar = "N";
                    var ejecutar = "N";
                    var ins = false;
                    var mod = false;
                    var del = false;
                    var eje = false;
                    var $g = $row.find("td:nth-child(2)");
                    var $u = $row.find("td:nth-child(3)");
                    var $d = $row.find("td:nth-child(4)");
                    var $e = $row.find("td:nth-child(5)");
                    $.each($g, function () {
                        ins = $g[0].children[0].checked;
                    });
                    $.each($u, function () {
                        mod = $u[0].children[0].checked;
                    });
                    $.each($d, function () {
                        del = $d[0].children[0].checked;
                    });
                    $.each($e, function () {
                        eje = $e[0].children[0].checked;
                    });
                    //if (ins == true || mod == true || del == true || eje == true) {
                    if (ins) {
                        acciones = "INS";
                        insertar = "S";
                    } else {
                        acciones = "DEL";
                        insertar = "N";
                    }
                    if (mod) {
                        modificar = "S";
                    }
                    if (del) {
                        eliminar = "S";
                    }
                    if (eje) {
                        ejecutar = "S";
                    }
                    if (id_permiso > 0 && id_rol > 0) {
                        $.ajax({
                            url: "/Roles/AllAgregarPermisos/",
                            type: "POST",
                            data: {
                                id: 0,
                                idPermiso: id_permiso,
                                idRol: id_rol,
                                insertar: insertar,
                                actualizar: modificar,
                                eliminar: eliminar,
                                ejecutar: ejecutar
                            }
                        }).done(function (data) {
                            if (data.success) {
                                agregar = true;
                            }
                            else {
                                agregar = false;
                                swal("Alerta!", data.mensaje, "warning");
                            }

                        });
                    }
                    //}
                });
                swal("Agregar Permiso", "Permisos Agregados con exito!", "success");
                //}
            });
            $("#ChkTodos").click(function () {
                $('input[type=checkbox]').each(function () {
                    if ($("#ChkTodos").is(":checked")) {
                        this.checked = true;
                    } else {
                        this.checked = false;
                    }
                });
            });
        });
    </script>
    <div class="card table-with-links table-responsive">
        <div class="card-header">
            <h2>Agregar Permisos</h2>
            <div class="card table-with-links table-responsive">
                <div class="card-header">
                    <div class="row">
                        <div class="col-sm-6">
                            <label>Rol</label>
                            @Html.DropDownList("id_rol", null, "Seleccionar...", new { @class = "form-control", @disabled = "disabled" })
                        </div>
                    </div>
                    <div class="pull-right">
                        <input type="checkbox" id="ChkTodos" name="ChkTodos" /> Marcar Todos                   
                    </div>

                </div>
            </div>

            <div class="card table-responsive">
                <div id="div_permisos" class="card-body table-responsive">
                    <table id="tblPermisos_" class="table">
                        <thead>
                            <tr>
                                <th>
                                    Paginas
                                </th>
                                <th>
                                    Insertar
                                </th>
                                <th>
                                    Modificar
                                </th>
                                <th>
                                    Eliminar
                                </th>
                                <th>
                                    Ejecutar
                                </th>
                                <th style="display:none;">
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Listado.Count() == 0)
                            {
                                <tr>
                                    <td>No existen registros</td>
                                </tr>
                            }
                            else
                            {
                                foreach (var item in Listado)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.nombre)
                                        </td>
                                        <td>
                                            <input type="checkbox" value="INS@item.id_pagina" id="idIns_@item.id_pagina" @(item.insert ? "checked='checked'" : "") />
                                        </td>
                                        <td>
                                            <input type="checkbox" value="UPD@item.id_pagina" id="idUpd_@item.id_pagina" @(item.update ? "checked='checked'" : "") />
                                        </td>
                                        <td>
                                            <input type="checkbox" value="DEL@item.id_pagina" id="idDel_@item.id_pagina" @(item.delete ? "checked='checked'" : "") />
                                        </td>
                                        <td>
                                            <input type="checkbox" value="EJE@item.id_pagina" id="idEje_@item.id_pagina" @(item.ejecutar ? "checked='checked'" : "") />
                                        </td>
                                        <td style="display:none;">
                                            @Html.DisplayFor(modelItem => item.id_pagina)
                                        </td>
                                    </tr>

                                }
                            }
                        </tbody>
                    </table>
                    <div class="pull-right">
                        <button type="submit" title="Guardar" class="btn btn-wd btn-facebook">
                            <i class="fa fa-check-square-o"></i>
                            Guardar
                        </button>
                        <a href="@Url.Action("Index", "Roles")" title="" class="btn btn-wd btn-info btn-outline" style="" data-original-title="Atras">
                            Cancelar
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

Jagua/Views/Roles/Create.cshtml
@model JaguaEntityModel.rol

@{
    ViewBag.Title = "Create";
}
<head>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        button {
            background: none;
            border: 0;
            color: #23CCEF;
        }
    </style>
</head>

<div class="card table-with-links table-responsive">
    <div class="card-header">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Nuevo Rol</h4>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="pull-right">
                <button type="submit" title="Guardar" class="btn btn-wd btn-facebook">
                    <i class="fa fa-check-square-o"></i>
                    Guardar
                </button>
                <a href="@Url.Action("Index", "Roles")" title="" class="btn btn-wd btn-info btn-outline" style="" data-original-title="Atras">
                    Cancelar
                </a>
            </div>

        </div>
        }

    </div>
</div>

Jagua/Views/Roles/Delete.cshtml
@model JaguaEntityModel.rol

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>rol</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Jagua/Views/Roles/Details.cshtml
﻿@model JaguaEntityModel.rol
@{
    ViewBag.Title = "Rol";
}
<head>
    @*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <style>
            button {
                background: none;
                border: 0;
                color: #23CCEF;
            }
        </style>*@
</head>
<div class="card table-with-links table-responsive">
    <div class="card-header">
        <fieldset disabled>
            @using (Html.BeginForm())
            {
                <div class="form-horizontal">
                    <h4>Rol</h4>
                    <div class="pull-right">
                    </div>
                    @Html.HiddenFor(model => model.id_rol)
                    <div class="form-group">
                        @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>
                </div>
            }
        </fieldset>
    </div>
</div>

Jagua/Views/Roles/Edit.cshtml
@model JaguaEntityModel.rol

@{
                /**/

                ViewBag.Title = "Edit";
}

<head>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        button {
            background: none;
            border: 0;
            color: #23CCEF;
        }
    </style>
</head>

<div class="card table-with-links table-responsive">
    <div class="card-header">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Editar Rol</h4>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id_rol)
            <div class="form-group">
                @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="pull-right">
                <button type="submit" title="Guardar" class="btn btn-wd btn-facebook">
                    <i class="fa fa-check-square-o"></i>
                    Guardar
                </button>
                <a href="@Url.Action("Index", "Roles")" title="" class="btn btn-wd btn-info btn-outline" style="" data-original-title="Atras">
                    Cancelar
                </a>
            </div>
        </div>
        }
    </div>
</div>