Jagua/Models/Facturacion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Jagua.Models
{
    //public class Facturacion
    //{
    //    public int id_ventas_cabecera { get; set; }
    //    public int id_caja { get; set; }
    //    public string comprobante { get; set; }
    //    public int id_cliente { get; set; }
    //    public decimal importe_total { get; set; }
    //    public decimal descuento { get; set; }
    //    public DateTime fecha { get; set; }
    //    public string usuario { get; set; }
    //}

    //public class ventas_cabecera
    //{
    //    public int id_ventas_cabecera { get; set; }
    //    public int id_caja { get; set; }
    //    public string comprobante { get; set; }
    //    public int id_cliente { get; set; }
    //    public int cant_articulos { get; set; }
    //    public string comentario { get; set; }
    //    public decimal descuento { get; set; }
    //    public int medio_pago { get; set; }
    //    public decimal importe_total { get; set; }
    //    public DateTime fecha { get; set; }
    //    public string usuario { get; set; }
    //}

    //public class ventas_detalle
    //{
    //    public int id_ventas_detalle { get; set; }
    //    public int id_venta_cabecera { get; set; }
    //    public int id_caja { get; set; }
    //    public string codigo_barra { get; set; }
    //    public int cantidad { get; set; }
    //    public int precio_unitario { get; set; }
    //    public string descripcion { get; set; }
    //    public string comentario { get; set; }
    //    public int importe { get; set; }
    //    public decimal descuento { get; set; }

    //}
}

Jagua/Controllers/FacturacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;
using Jagua.Models;
using JaguaEntityModel;
using PagedList;


namespace Jagua.Controllers
{
    public class FacturacionController : Controller
    {
        private JaguaEntities db = new JaguaEntities();

        // GET: Facturacion
        [HttpGet]
        public ActionResult Index(int? page)
        {
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1; //operador ternario de consulta

            //var x = DataTableExtensions.DataTableToCode(new Jagua.Datasets.Ticket.DT_CabeceraDataTable());
            //var y = DataTableExtensions.DataTableToCode(new Jagua.Datasets.Ticket.DT_DetalleDataTable());


            var operaciones = db.ventas_cabecera.Include(d => d.caja).Include(e => e.cliente).Include(f => f.medio_pago).Where(q => q.cobrado == "S");

            return View(operaciones.ToList().OrderByDescending(n => n.fecha).ToPagedList(pageIndex, pageSize));
        }

        [HttpPost]
        public ActionResult Index(FormCollection fc, int? page)
        {
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

            var operaciones = db.ventas_cabecera.Where(q => q.cobrado == "S").ToList();
            var fecha_desde = fc["txtFechaDesde"]; // A traves del fc, obtengo el valor de la caja de texto
            var fecha_hasta = fc["txtFechaHasta"]; // A traves del fc, obtengo el valor de la caja de texto
            var estado = fc["ddlEstado"]; // A traves del fc, obtengo el valor de la caja de texto
            var cliente = fc["txtCliente"]; // A traves del fc, obtengo el valor de la caja de texto
            var factura = fc["txtFactura"]; // A traves del fc, obtengo el valor de la caja de texto
            var producto = fc["txtProducto"];

            if (!string.IsNullOrEmpty(fecha_desde)) // pregunto si no esta vacio la variable nombre
            {
                var fecha = DateTime.Parse(fecha_desde);
                operaciones = operaciones.Where(q => q.fecha >= fecha).ToList();//pregunta si el campo es igual al filtro
            }
            if (!string.IsNullOrEmpty(fecha_hasta))
            {
                fecha_hasta = fecha_hasta + " 23:59:59"; //23.59 para que tome busqueda del dia
                var fecha = DateTime.Parse(fecha_hasta);
                operaciones = operaciones.Where(q => q.fecha <= fecha).ToList();
            }
            if (!string.IsNullOrEmpty(estado))
            {
                operaciones = operaciones.Where(q => q.estado == estado).ToList();
            }
            //if (!string.IsNullOrEmpty(cliente))
            //{
            //    operaciones = operaciones.Where(q => q.persona.nombre.Contains(cliente) || q.cliente.persona.apellido.Contains(cliente) || q.cliente.persona.nro_documento==cliente ).ToList();
            //}
            if (!string.IsNullOrEmpty(factura))
            {
                operaciones = operaciones.Where(q => q.comprobante.Contains(factura)).ToList();
            }
            //if (!string.IsNullOrEmpty(producto))
            //{
            //    foreach (var item in operaciones) {
            //        var detalle_productos = db.ventas_detalle.Where(x => x.id_venta_cabecera == item.id_ventas_cabecera).ToList();
            //        detalle_productos = detalle_productos.Where(q => q.descripcion.Contains(producto)).ToList();
            //    }
            //}
            //aca le asigno a la cajita la variable que contiene la busqueda, para que aparezca al retornar
            //ViewBag.txtNombre = nombre;

            //retorno la vista filtrada
            return View(operaciones.OrderByDescending(n => n.fecha).ToPagedList(pageIndex, pageSize));

        }

        [HttpGet]
        public ActionResult CargarVenta()
        {
            var id_usuario = Jagua.Clases.SessionManager.SessionData.id_usuario;
            var cajas = db.caja.Where(x => x.id_usuario == id_usuario).ToList();
            if (cajas.Count() > 0) {
                var usuario = Jagua.Clases.SessionManager.SessionData.usuario.ToLower();
                var aperturas = db.apertura_cierre.Where(x => x.usuario_apertura.ToLower() == usuario & x.fecha_cierre == null).ToList();
                if (aperturas.Count() > 0)
                {
                    ViewBag.id_tipo_comprobante = new SelectList(db.tipo_comprobante.ToList(), "id_tipo_comprobante", "descripcion", 3);
                    ViewBag.id_medio_pago = new SelectList(db.medio_pago.ToList(), "id_medio_pago", "descripcion");
                    ViewBag.id_tipo_documento = new SelectList(db.tipo_documento.ToList(), "id_tipo_documento", "abreviatura");
                    return View();
                }
                else
                {
                    TempData["msg"] = "<script>swal({text: 'Debe realizar la apertura de una caja',type: 'warning'});</script>";
                    return RedirectToAction("AperturaCierre", "Cajas");
                }
            }
            else {
                TempData["msg"] = "<script>swal({text: 'No posee una caja habilitada para este usuario, habilite una caja',type: 'warning'});</script>";
                return RedirectToAction("Create", "Cajas");
            }
        }

        [HttpPost]
        public JsonResult CargarVenta(ventas_cabecera cabecera, ventas_detalle[] datosDetalle) //recibo como parametro la cabecera y el detalle que me envia desde la vista
        {
            ViewBag.id_tipo_comprobante = new SelectList(db.tipo_comprobante.ToList(), "id_tipo_comprobante", "descripcion");
            ViewBag.id_medio_pago = new SelectList(db.medio_pago.ToList(), "id_medio_pago", "descripcion");
            ViewBag.id_tipo_documento = new SelectList(db.tipo_documento.ToList(), "id_tipo_documento", "abreviatura");
            try
            {
                if (cabecera != null && datosDetalle != null)
                {
                    cabecera.usuario_alta = Clases.SessionManager.SessionData.usuario.ToLower();
                    cabecera.fecha_alta = DateTime.Now;
                    db.ventas_cabecera.Add(cabecera);
                    db.SaveChanges();

					var nro_item = 0;

					//se guarda el detalle
					foreach (var datosdetalle in datosDetalle)
                    {
                        var guardarDetalle = new ventas_detalle();
                        guardarDetalle.id_venta_cabecera = cabecera.id_ventas_cabecera;
						guardarDetalle.nro_item = nro_item + 1;
                        guardarDetalle.id_producto = datosdetalle.id_producto;
                        guardarDetalle.codigo_barra = datosdetalle.codigo_barra;
                        guardarDetalle.descripcion = datosdetalle.descripcion;
                        guardarDetalle.cantidad = datosdetalle.cantidad;
                        guardarDetalle.precio_unitario = datosdetalle.precio_unitario;
                        guardarDetalle.iva10 = datosdetalle.iva10;
                        guardarDetalle.iva5 = datosdetalle.iva5;
                        guardarDetalle.exentas = datosdetalle.exentas;
                        guardarDetalle.gravadas = datosdetalle.gravadas;
                        guardarDetalle.subtotal = datosdetalle.subtotal;
						db.ventas_detalle.Add(guardarDetalle);
                        db.SaveChanges();
                        //Actualizar el stock
                        var producto = db.producto.Where(x => x.id_producto == datosdetalle.id_producto).FirstOrDefault();
						producto.stock = (producto.stock - datosdetalle.cantidad);
						db.Entry(producto).State = EntityState.Modified;
						db.SaveChanges();
					}
                    db.SaveChanges();

                    //CALCULAMOS LOS PUNTOS ---------------
                    Clases.Puntajes.VerificarPuntajes(cabecera.id_cliente, cabecera.id_ventas_cabecera);
                    //-------------------------------------

                    Imprimir(cabecera, datosDetalle);

                    return Json(new { Status = "Success" });
                }
                else
                {
                    ModelState.AddModelError("", "No se puede registrar los cabecera sin detalle de ventas ");
                    var result = "0";
                    return Json(result);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error inesperado, contacte con el administrador: " + ex.Message);
                var result = "1";
                return Json(result);
            }
            
        }

        //Metodo para usar el autocomplete de jquery ui en clientes
        public JsonResult ClienteSearch(string search, FormCollection fc)
       { 
            if(!String.IsNullOrEmpty(search))
            {
                var ClienteList = (from a in db.persona
                                   join b in db.cliente on a.id_persona equals b.id_persona
                            where (a.nro_documento.Contains(search) || a.nombre.Contains(search) || a.apellido.Contains(search)) && a.id_cat_persona == 1 //categoria persona 1 es cliente
                            select new { a.nro_documento, a.nombre, a.apellido, b.id_cliente});
            return Json(ClienteList, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return null;
            }

        }

        public JsonResult ProductDetails(string search)
        {
            if (!String.IsNullOrEmpty(search))
            {
                var ProductosList = (from N in db.producto
                                   where (N.id_producto.ToString().Contains(search) || N.descripcion.ToLower().Contains(search.ToLower()) || N.codigo_barra.Contains(search))

Jagua/Views/Facturacion/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<JaguaEntityModel.ventas_cabecera>

@{
    ViewBag.Title = "Index";
    //var id_usuario = Jagua.Clases.SessionManager.SessionData.id_usuario;
    //var aperturas
}
<head>
    <script type="text/javascript">
        function Anular(item) {
            swal({
                title: "Estas Seguro?",
                text: "El registro se anulara!",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn btn-info btn-fill",
                confirmButtonText: "Si, anular!",
                cancelButtonClass: "btn btn-danger btn-fill",
                cancelButtonText: "Cancelar",
                closeOnConfirm: false,
            }, function (isConfirm) {
                if (isConfirm) {
                    $("#frmList").attr("action", "/Facturacion/Anular/" + item);
                    $("#frmList").submit();
                    swal({ text: "El registro se anulo", type: "success" });
                    window.location.reload();
                } else {
                    swal({ text: "Cancelado", type: "info" });
                }
            });
        }
        $(document).ready(function () {
            $("[name=btnBuscar]").click(function () {
                $("#frmList").attr("action", "/Facturacion/Index/");
                $("#frmList").submit();

            });
        });
    </script>
</head>
<body>
    <div class="container-fluid">
        <div class="card strpied-tabled-with-hover">
            <div class="card-header">
                @using (Html.BeginForm("Index", "Facturacion", FormMethod.Post, new { id = "frmList" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="pull-right" style="margin-right: 10px;">
                        <a href="@Url.Action("CargarVenta", "Facturacion")" rel="tooltip" style="background-color:mediumpurple" class="btn btn-wd" data-original-title="Agregar Registro">
                            <i class="fa fa-sellsy" aria-hidden="true"></i>Cargar Operación
                        </a>
                    </div>
                    <h4><i class="fa fa-cart-plus" style="color:mediumpurple"></i> &nbsp;<b>Operaciones</b></h4>
                    <hr />
                    <div class="row">
                        <div class="col-sm-3">
                            <label>Fecha Desde</label>
                            @Html.TextBox("txtFechaDesde", "", new { @class = "form-control", type = "date" })
                        </div>
                        <div class="col-sm-3">
                            <label>Fecha Hasta</label>
                            @Html.TextBox("txtFechaHasta", "", new { @class = "form-control", type = "date" })
                        </div>
                        <div class="col-md-3">
                            <label>Estado</label>
                            @Html.DropDownList("ddlEstado", new SelectList(new List<object>
                            {
                                new { value = "", text = "--Seleccionar--"},
                                new { value = "C", text = "COBRADO"},
                                new { value = "A", text = "ANULADO"},
                                },
                            "value","text",(SelectList)ViewBag.ddlEstado),
                            new { @class = "form-control"})
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-3">
                            <label>Cliente</label>
                            @Html.TextBox("txtCliente", (String)ViewBag.txtCliente, new { @class = "form-control", @placeholder = "Cedula, Nombre, Apellido", @maxlength = "10" })
                        </div>
                        <div class="col-sm-3">
                            <label>Factura</label>
                            @Html.TextBox("txtFactura", (String)ViewBag.txtFactura, new { @class = "form-control", @placeholder = "Nro Factura", @maxlength = "10" })
                        </div>
                        <button type="submit" name="btnBuscar" title="Buscar registros" class="btn btn-simple btn-success btn-outline" style="margin-top:30px;height:30px">
                            <i class="nc-icon nc-zoom-split icon-bold" aria-hidden="true"></i>
                        </button>
                        &nbsp;
                        <button type="submit" name="btnBuscar" title="Buscar registros" class="btn btn-simple btn-warning btn-outline" style="margin-top:30px;height:30px">
                            <i class="nc-icon nc-paper-2 icon-bold" aria-hidden="true"></i>&nbsp;Reporte
                        </button>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="card strpied-tabled-with-hover">
            <div class="card-body table-full-width table-responsive">
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>
                                Id
                            </th>
                            <th>
                                Fecha
                            </th>
                            <th>
                                Caja
                            </th>
                            <th>
                                Comprobante
                            </th>
                            <th>
                                Cliente
                            </th>
                            <th>
                                Importe Total
                            </th>
                            <th>
                                Medio Pago
                            </th>
                            <th>
                                Usuario
                            </th>
                            <th>
                                Estado
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Count() == 0)
                        {
                            <tr>
                                <td>No existen registros</td>
                            </tr>
                        }
                        else
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.id_ventas_cabecera)
                                    </td>
                                    <td>
                                        @item.fecha.Value.ToString("dd/MM/yyyy")
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.id_caja)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.comprobante)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.cliente.persona.nombre)
                                        @Html.DisplayFor(modelItem => item.cliente.persona.apellido)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.importe_total)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.medio_pago.descripcion)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.usuario_alta)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.estado)
                                    </td>
                                    <td>
                                        <div class="row">
                                            <h5 @(item.estado != "A" ? "display" : "hidden") style="color:red; font-weight:bolder; margin-bottom:0px;" onmouseover="this.style.cursor='pointer';" aria-hidden="true" rel="tooltip" data-original-title="Anular" onclick="Anular(@item.id_ventas_cabecera)">A</h5>
                                            <a href="@Url.Action("ImprimirTicket", "Facturacion", new { id = item.id_ventas_cabecera})" title="" rel="tooltip" data-original-title="Imprimir" target="_blank" style="color:deepskyblue;font-size:15px;"><i class="fa fa-print" aria-hidden="true"></i></a>
                                        </div>
                                        
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
                <hr />
                <div class="pull-right" style="margin-right:10px">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
                </div>
            </div>
        </div>
    </div>
</body>