Jagua/Controllers/CiudadesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JaguaEntityModel;
using PagedList;

namespace Jagua.Controllers
{
    public class CiudadesController : Controller
    {
        private JaguaEntities db = new JaguaEntities();

        // GET: Ciudades
        public ActionResult Index(int? page)
        {
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

            ViewBag.ddlDepartamento = new SelectList(db.departamento.ToList(), "id_departamento", "descripcion");
            var ciudad = db.ciudad.Include(d => d.departamento);
            return View(ciudad.OrderByDescending(n => n.descripcion).ToPagedList(pageIndex, pageSize));
        }

        [HttpPost]
        public ActionResult Index(FormCollection fc, int? page)
        {
            int pageSize = 10;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

            var ciudades = db.ciudad.ToList(); // genero una lista de ciudades
            var nombre = fc["txtNombre"]; // A traves del fc, obtengo el valor de la caja de texto
            int departamento = string.IsNullOrEmpty(fc["ddlDepartamento"].ToString()) ? Convert.ToInt32("0") : Convert.ToInt32(fc["ddlDepartamento"].ToString());

            if (!string.IsNullOrEmpty(nombre)) // pregunto si no esta vacio la variable nombre
            {
                //contains es la funcion que filtra la busqueda que contiene el metodo de busqueda
                ciudades = ciudades.Where(q => q.descripcion.ToLower().Contains(nombre.ToLower())).ToList(); 
            }
            if (departamento > 0)
            {
                ciudades = ciudades.Where(x => x.id_departamento == departamento).ToList();
            }


            //aca le asigno a la cajita la variable que contiene la busqueda, para que aparezca al retornar
            ViewBag.txtNombre = nombre;
            //devuelvo el ddl como ultimo argumento la variable de busqueda
            ViewBag.ddlDepartamento = new SelectList(db.departamento.ToList(), "id_departamento", "descripcion", departamento); 
            //retorno la vista filtrada
            return View(ciudades.OrderByDescending(n => n.descripcion).ToPagedList(pageIndex, pageSize));

        }

        // GET: Ciudades/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ciudad ciudad = db.ciudad.Find(id);
            if (ciudad == null)
            {
                return HttpNotFound();
            }
            return View(ciudad);
        }

        // GET: Ciudades/Create
        public ActionResult Create()
        {
            ViewBag.id_departamento = new SelectList(db.departamento, "id_departamento", "descripcion");
            return View();
        }

        // POST: Ciudades/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_ciudad,descripcion,id_departamento")] ciudad ciudad)
        {
            if (ModelState.IsValid)
            {
                ciudad.descripcion = Jagua.Clases.Comun.UppercaseFirst(ciudad.descripcion); //Esta linea lo que hace es pone la primera letra de cada palabra en mayuscula
                ciudad.estado = "A";
                ciudad.usuario_alta = Clases.SessionManager.SessionData.usuario.ToLower();
                ciudad.fecha_alta = DateTime.Now;
                db.ciudad.Add(ciudad);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_departamento = new SelectList(db.departamento, "id_departamento", "descripcion", ciudad.id_departamento);
            return View(ciudad);
        }

        // GET: Ciudades/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ciudad ciudad = db.ciudad.Find(id);
            if (ciudad == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_departamento = new SelectList(db.departamento, "id_departamento", "descripcion", ciudad.id_departamento);
            return View(ciudad);
        }

        // POST: Ciudades/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_ciudad,descripcion,id_departamento,estado,usuario_alta,fecha_alta")] ciudad ciudad)
        {
            if (ModelState.IsValid)
            {
                ciudad.descripcion = Jagua.Clases.Comun.UppercaseFirst(ciudad.descripcion); //Esta linea lo que hace es pone la primera letra de cada palabra en mayuscula
                ciudad.usuario_mod = Clases.SessionManager.SessionData.usuario.ToLower();
                ciudad.fecha_mod = DateTime.Now;
                db.Entry(ciudad).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_departamento = new SelectList(db.departamento, "id_departamento", "descripcion", ciudad.id_departamento);
            return View(ciudad);
        }

        // GET: Ciudades/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ciudad ciudad = db.ciudad.Find(id);
            if (ciudad == null)
            {
                return HttpNotFound();
            }
            return View(ciudad);
        }

        // POST: Ciudades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ciudad ciudad = db.ciudad.Find(id);
            db.ciudad.Remove(ciudad);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public void DisableConfirmed(int id)
        {
            ciudad ciudad = db.ciudad.Find(id);
            ciudad.estado = "I";
            ciudad.usuario_mod = Jagua.Clases.SessionManager.SessionData.usuario;
            ciudad.fecha_mod = DateTime.Now;
            db.SaveChanges();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Jagua/Views/Ciudades/Create.cshtml
@model JaguaEntityModel.ciudad

@{
    ViewBag.Title = "Create";
}
<head>

</head>
<body>
    <div class="container-fluid">
        <div class="card strpied-tabled-with-hover">
            <div class="card-header ">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-horizontal">
                        <h4><i class="fa fa-map-pin" style="color:mediumpurple"></i> &nbsp;<b>Nueva Ciudad</b></h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <div class="col-md-3">
                                <label>Descripción</label>
                                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "Descripción", @maxlength = "50" } })
                                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3">
                                <label>Departamento</label>
                                @Html.DropDownList("id_departamento", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.id_departamento, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <hr />
                    <div class="pull-right">
                        <button type="submit" title="Guardar" class="btn btn-wd btn-facebook">
                            <i class="fa fa-check-square-o"></i>
                            Guardar
                        </button>
                        <a href="@Url.Action("Index", "Ciudades")" title="" class="btn btn-wd btn-info btn-outline" style="" data-original-title="Atras">
                            Cancelar
                        </a>
                    </div>
                }

            </div>
        </div>
    </div>
</body>

Jagua/Views/Ciudades/Edit.cshtml
@model JaguaEntityModel.ciudad

@{
    ViewBag.Title = "Edit";
}

<head>
</head>

<body>
    <div class="container-fluid">
        <div class="card strpied-tabled-with-hover">
            <div class="card-header ">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-horizontal">
                        <h4><i class="fa fa-map-pin" style="color:mediumpurple"></i> &nbsp;<b>Editar Ciudad</b></h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id_ciudad)
                        @Html.HiddenFor(model => model.usuario_alta)
                        @Html.HiddenFor(model => model.fecha_alta)
                        <div class="form-group">
                            <div class="col-md-3">
                                <label>Descripción</label>
                                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "Descripción", @maxlength = "50" } })
                                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3">
                                <label>Departamento</label>
                                @Html.DropDownList("id_departamento", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.id_departamento, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3">
                                <label>Estado</label>
                                @Html.DropDownList("estado", new SelectList(new List<object>
                                    {
                                    new { value = "", text = "--Seleccionar--"},
                                    new { value = "A", text = "ACTIVO"},
                                    new { value = "I", text = "INACTIVO"},
                                    },
                                    "value",
                                    "text"), new { @class = "form-control", required = "required" })
                            </div>
                        </div>
                    </div>
                    <hr />
                    <div class="pull-right">
                        <button type="submit" title="Guardar" class="btn btn-wd btn-facebook">
                            <i class="fa fa-check-square-o"></i>
                            Guardar
                        </button>
                        <a href="@Url.Action("Index", "Ciudades")" title="" class="btn btn-wd btn-info btn-outline" style="" data-original-title="Atras">
                            Cancelar
                        </a>
                    </div>
                }

            </div>
        </div>
    </div>
</body>

Jagua/Views/Ciudades/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<JaguaEntityModel.ciudad>

@{
    ViewBag.Title = "Index";
}
<head>
    <script type="text/javascript">
        $(document).ready(function () {
            $("[name=btnBuscar]").click(function () {
                $("#frmList").attr("action", "/Ciudades/Index/");
                $("#frmList").submit();

            });
        });
    </script>
    <script type="text/javascript">
		function Desactivar(item) {
			swal({
				title: "Estas Seguro?",
				text: "El registro se desactivara!",
				type: "warning",
				showCancelButton: true,
				confirmButtonClass: "btn btn-info btn-fill",
				confirmButtonText: "Si, desactivarlo!",
				cancelButtonClass: "btn btn-danger btn-fill",
				cancelButtonText: "Cancelar",
				closeOnConfirm: false,
			}, function (isConfirm) {
                debugger
                if (isConfirm) {
                    $("#frmList").attr("action", "/Ciudades/DisableConfirmed/" + item);
                    $("#frmList").submit();
                    swal({
                        text: "El registro fue desactivado",
                        type: "success"
                    });
                    window.location.reload();
                } else {
                    swal({
                        text: "Cancelado",
                        type: "warning"
                    });
                }
			});
        } /*Fin Function*/

        $(document).ready(function () {
            $("[name=btnBuscar]").click(function () {
                $("#frmList").attr("action", "/Ciudades/Index/");
                $("#frmList").submit();
			});
        });
    </script>
</head>
<body>
    <div class="container-fluid">
        <div class="card strpied-tabled-with-hover">
            <div class="card-header ">
                @using (Html.BeginForm("Index", "Ciudades", FormMethod.Post, new { id = "frmList" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="pull-right">
                        <a href="@Url.Action("Create", "Ciudades")" class="btn btn-wd btn-info btn-outline" title="" rel="tooltip" data-original-title="Agregar Registro">
                            <i class="fa fa-plus" aria-hidden="true"></i>Nueva Ciudad
                        </a>
                    </div>
                    <h4><i class="fa fa-map-pin" style="color:mediumpurple"></i> &nbsp;<b>Ciudades</b></h4>
                    <hr />
                    <div class="row">
                        <div class="col-sm-3">
                            <label>Ciudad</label>
                            @Html.TextBox("txtNombre", (String)ViewBag.txtNombre, new { @class = "form-control" })
                        </div>
                        <div class="col-sm-3">
                            <label>Departamento</label>
                            @Html.DropDownList("ddlDepartamento", null, "--Seleccionar--", new { @class = "form-control" })
                        </div>
                        <button type="submit" name="btnBuscar" title="Buscar registros" class="btn btn-simple btn-success btn-outline" style="margin-top: 25px;">
                            <i class="nc-icon nc-zoom-split icon-bold" style="font-size: 20px" aria-hidden="true"></i>
                        </button>
                    </div>
                }
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="card strpied-tabled-with-hover">
            <div class="card-body table-full-width table-responsive">
                <table class="table table-hover table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Ciudad</th>
                                <th>Departamento</th>
                                <th>Estado</th>
                                <th>Usuario Alta</th>
                                <th>Fecha Alta</th>
                                <th>Usuario Mod</th>
                                <th>Fecha Mod</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Count() == 0)
                            {
                                <tr>
                                    <td>No existen registros</td>
                                </tr>
                            }
                            else
                            {
                                foreach (var item in Model)
                                {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.id_ciudad)</td>
                                    <td>@Html.DisplayFor(modelItem => item.descripcion)</td>
                                    <td>@Html.DisplayFor(modelItem => item.departamento.descripcion)</td>
                                    <td>@Html.DisplayFor(modelItem => item.estado)</td>
                                    <td>@Html.DisplayFor(modelItem => item.usuario_alta)</td>
                                    <td>@Html.DisplayFor(modelItem => item.fecha_alta)</td>
                                    <td>@Html.DisplayFor(modelItem => item.usuario_mod)</td>
                                    <td>@Html.DisplayFor(modelItem => item.fecha_mod)</td>
                                    <td>
                                        <a href="@Url.Action("Edit", "Ciudades", new {id = item.id_ciudad})" style="color:deepskyblue"><i class="fa fa-edit" aria-hidden="true"></i></a>
                                        <i class="fa fa-arrow-down" @(item.estado != "I" ? "display" : "hidden") style="color:red" onmouseover="this.style.cursor='pointer';" onclick="Desactivar(@item.id_ciudad)" aria-hidden="true" rel="tooltip" data-original-title="Anular"></i>
                                    </td>
                                </tr>
                                }
                            }
                        </tbody>
                    </table>
                    <div class="pull-right">
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilter = ViewBag.CurrentFilter }))
                    </div>
            </div>
        </div>
    </div>
</body>